language: python
notifications:
  email: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - wget -O snappy-1.1.2.tar.gz -- "https://docs.google.com/uc?authuser=0&id=0B0xs9kK-b5nMOWIxWGJhMXd6aGs&export=download"
  - tar -xf snappy-1.1.2.tar.gz
  - cd snappy-1.1.2 && ./configure && make all install
  - pip install -r requirements.txt --use-mirrors
script:
  - make
  - make samples
